### ISSUE TITLE
Micropython stuck loading

### ISSUE THREAD

**Issue by mrdowling** [arduino-libraries/Arduino_Alvik#10]
My Arduino Lab for Micropython app is stuck on loading when I initially open it. I'm running MAC OS. I was working fine a few days ago. I recently added some file locations and the app started behaing like this.

<img width="1728" alt="Screenshot 2024-07-17 at 10 34 14 AM" src="https://github.com/user-attachments/assets/31e8d599-b987-4823-bd72-970aab326e61">

**Comment by gbr1** [comment]
@mrdowling as already told you some days ago, this is the arduino language alvik library repository, please do not open issues related to micropython editor here.
