### ISSUE TITLE
Using the Grove Connector

### ISSUE THREAD

**Issue by sswartley** [arduino-libraries/Arduino_Alvik#11]
Hello,

Could you provide an example of using the Grove connector. Specifically, I would like to display sensor readings on the Seeed Studio Grove - OLED Display 0.96". Thanks!

**Comment by gbr1** [comment]
Hi @sswartley !
Please check if your display works at 3V3 because Grove connectors on Alvik are at 3V3. 
Then you can use any already available example to work with it, because Nano ESP32 A4 and A5 pins  (Wire) are connected to Grove/Qwiic connectors

**Comment by gbr1** [comment]
@sswartley in the next release there will be [this example](https://github.com/arduino-libraries/Arduino_Alvik/blob/dev/examples/modulino/modulino.ino) with i2c exposed as `alvik.i2c`

About docs, check the following, it is for micropython but very similar:
https://docs.arduino.cc/tutorials/alvik/api-overview/

and the header file:
https://github.com/arduino-libraries/Arduino_Alvik/blob/main/src/Arduino_Alvik.h#L176-L236

**Comment by sswartley** [comment]
Hi @gbr1 !

Thank you for your quick response and help. I am interested in showing educators how they can create robots using Arduino Alvik and [Vernier Go Direct sensors](https://www.vernier.com/product-category/?category=sensors). We have an [Arduino library called GDXLib](https://github.com/VernierST/GDXLib) that allows BLE communication with the sensors. The sensors could be used to create some unique robots (for example, a robot controlled by grip strength, or a robot that is sent to test the pH of a solution, or a robot that determines which way is magnetic north and "migrates").

If you have any thoughts, ideas, or questions, feel free to contact me at sswartley@vernier.com
