### ISSUE TITLE
Arduino Lab for MicroPython stuck loading. MACOS

### ISSUE THREAD

**Issue by mrdowling** [arduino-libraries/Arduino_Alvik#9]
I tried to open the Arduino Lab for Micropython app yesterday and it was stuck in the loading files screen. 

It was working earlier in the day. I noticed the problem right after creating and saving new programs.

<img width="1728" alt="Screenshot 2024-07-16 at 9 58 55 AM" src="https://github.com/user-attachments/assets/7a7d1127-e21a-4119-ba3e-dea5bf40af9c">

**Comment by gbr1** [comment]
Hi @mrdowling , this issue is not related to Alvik neither Alvik library in C.
Please reopen on Arduino Lab for Micropython here: https://github.com/arduino/lab-micropython-editor

**Comment by gbr1** [comment]
Refer and duplicate at [#128](https://github.com/arduino/lab-micropython-editor/issues/128)
